<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Our Journey</name>
   <tag></tag>
   <elementGuidId>dca0a961-c8cd-4562-8cbc-e74f8ad598f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button.red.wow.fadeIn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed8a8a58-6c20-4e63-ab50-89da5f218397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button red wow fadeIn</value>
      <webElementGuid>d2df0da4-b4d3-4711-b715-038861969949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/about-us</value>
      <webElementGuid>95fd524d-1356-4f07-8838-6a587728ee15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Our Journey</value>
      <webElementGuid>1736e4e8-e4c8-42e8-952a-e94552b52847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;content&quot;]/div[@class=&quot;style_containerJourney___kC0Q&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;style_journeyWrapper__f4eeS&quot;]/a[@class=&quot;button red wow fadeIn&quot;]</value>
      <webElementGuid>03e31c0a-6f95-4ee4-b191-9c2cce0892ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/a</value>
      <webElementGuid>28789af5-6d90-4ad6-bb0f-a73eb42f3000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Our Journey')]</value>
      <webElementGuid>b3ddbb1d-60e3-48c8-ae8c-2c5c39c89b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We Provide A Cutting Edge Solution For What You Need'])[1]/following::a[1]</value>
      <webElementGuid>b88c56cc-7839-4a9f-b276-164d3c338049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A leading Professional Tech Company'])[1]/following::a[1]</value>
      <webElementGuid>f17a2492-505d-4d66-ad73-d891139924b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product &amp; Solutions'])[2]/preceding::a[1]</value>
      <webElementGuid>64d3a7d5-8a00-4936-b69f-43adb3a8f7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chatbot'])[1]/preceding::a[1]</value>
      <webElementGuid>09bdf6dd-9256-4b73-b581-6778a562a46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Our Journey']/parent::*</value>
      <webElementGuid>2819b1f0-37b4-42f7-b9f6-5255fca2e366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/about-us')])[2]</value>
      <webElementGuid>af004f67-e784-45a1-a434-b4d61175a4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>e0eeba64-70a2-4611-a892-84f34a9eb78f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/about-us' and (text() = 'Our Journey' or . = 'Our Journey')]</value>
      <webElementGuid>9d9a4116-1dbb-400b-85e3-f0e690e8aecb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
